Exer3/Controllers/LaboratoireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Exer3.Models;
using Exer3.Extensions;

namespace Exer3.Controllers
{
    public class LaboratoireController : Controller
    {
        public ActionResult RapportIncident()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EnvoyeMessage(RapportIncident p_rapportIncident)
        {
            string nomUtilisateur = p_rapportIncident.Nom;
            string identifiant = p_rapportIncident.Identifiant;
            string courriel = p_rapportIncident.Courriel;
            string typeProblèmes = p_rapportIncident.Probleme.ToString();
            string plateforme = p_rapportIncident.PlateformeErreur.ToString();
            string descriptionProblème = p_rapportIncident.DescriptionComportement;

            string body = string.Format(
                                    "Nom d'utilisateur: {0}" +
                                    "\nNuméro DA: {1}" +
                                    "\n\nType de problème: {2}" +
                                    "\nPlateforme causant l’erreur: {3}" +
                                    "\nDescription du problème: {4}",
                                    nomUtilisateur, identifiant, typeProblèmes, plateforme, descriptionProblème);

            Mail.MailHelper.EnvoyeMessage("Type de probleme", "nimporteQuoi", "giguere.vero@gmail.com");
            return RedirectToAction("Laboratoire/RapportIncident");
        }
    }
}

Exer3/Controllers/NousJoindreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Exer3.Controllers
{
    public class NousJoindreController : Controller
    {
        public IActionResult NousJoindre()
        {
            return View();
        }
    }
}

Exer3/Controllers/ServeurController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Exer3.Controllers
{
    public class ServeurController : Controller
    {
        public IActionResult ListeServeurs()
        {
            return View();
        }
    }
}

Exer3/Controllers/TutoratController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Exer3.Models;
using Exer3.Extensions;

namespace Exer3.Controllers
{
    public class TutoratController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult DemandeTuteur()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DemandeTuteur(DemandeTuteur etudiant)
        {
            CreerDemande(etudiant);
            return RedirectToAction("Index");
        }

        public void CreerDemande(DemandeTuteur etudiant)
        {
            List<DemandeTuteur> etudiants = HttpContext.Session.Get<List<DemandeTuteur>>("Etudiants");
            etudiants.Add(etudiant);
            HttpContext.Session.Set("Etudiants", etudiants);
        }

        public ActionResult OffrirTuteur()
        {
            return View();
        }

        [HttpPost]
        public ActionResult OffrirTuteur(OffreTuteur etudiant)
        {
            AjoutTuteur(etudiant);
            return RedirectToAction("Index");
        }

        public void AjoutTuteur(OffreTuteur etudiant)
        {
            List<OffreTuteur> etudiants = HttpContext.Session.Get<List<OffreTuteur>>("Etudiants");
            etudiants.Add(etudiant);
            HttpContext.Session.Set("Etudiants", etudiants);
        }
       
    }
}

Exer3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TP1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <!--external css-->
    <link href="~/fontawesome/css/all.css" rel="stylesheet" />
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- <link rel="stylesheet" href="~/css/styles.css" /> -->
    <!-- <link rel="stylesheet" href="~/css/style-responsive.css"> -->
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Accueil</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Laboratoires
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Laboratoire" asp-action="RapportIncident">Rapport d'incident</a></li>
                            <li><a a target="_blank" href="~/documents/Horaires_des_locaux.pdf">Horaires</a></li>
                        </ul>
                    </li>
                    <li><a href="http://www1.cstjean.qc.ca/emploisstages">Offres d'emploi et offres ATE</a></li>
                    <li><a href="https://cstjean.onthehub.com/">Magasin de logiciels</a></li>
                    <li><a asp-controller="Serveur" asp-action="ListeServeurs">Serveurs du département</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Tutorat
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Tutorat" asp-action="DemandeTuteur">Demander un tuteur</a></li>
                            <li><a asp-area="" asp-controller="Tutorat" asp-action="OffrirTuteur">Offrir ses services de tuteur</a></li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="NousJoindre" asp-action="NousJoindre">Nous joindre</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Véronique Giguère</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>